question_data = [
    {
        "type": "multiple", "difficulty": "easy",
        "category": "Science: Computers",
        "question": "The numbering system with a radix of 16 is more commonly referred to as ",
        "correct_answer": "Hexidecimal",
        "incorrect_answers": ["Binary", "Duodecimal", "Octal"]
    },
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "What is the name of the default theme that is installed with Windows XP?", "correct_answer": "Luna",
     "incorrect_answers": ["Neptune", "Whistler", "Bliss"]},
    {"type": "multiple", "difficulty": "easy", "category": "Science: Computers",
     "question": "In web design, what does CSS stand for?", "correct_answer": "Cascading Style Sheet",
     "incorrect_answers": ["Counter Strike: Source", "Corrective Style Sheet", "Computer Style Sheet"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "question": "Linux was first created as an alternative to Windows XP.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "All of the following programs are classified as raster graphics editors EXCEPT:",
     "correct_answer": "Inkscape",
     "incorrect_answers": ["Paint.NET", "GIMP", "Adobe Photoshop"]},
    {"type": "multiple", "difficulty": "hard", "category": "Science: Computers",
     "question": "Who invented the &quot;Spanning Tree Protocol&quot;?", "correct_answer": "Radia Perlman",
     "incorrect_answers": ["Paul Vixie", "Vint Cerf", "Michael Roberts"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "The name of technology company HP stands for what?", "correct_answer": "Hewlett-Packard",
     "incorrect_answers": ["Howard Packmann", "Husker-Pollosk", "Hellman-Pohl"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "What did the name of the Tor Anonymity Network orignially stand for?",
     "correct_answer": "The Onion Router",
     "incorrect_answers": ["The Only Router", "The Orange Router", "The Ominous Router"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "How many bytes are in a single Kibibyte?", "correct_answer": "1024",
     "incorrect_answers": ["2400", "1000", "1240"]},
    {"type": "multiple", "difficulty": "easy", "category": "Science: Computers",
     "question": "Which computer language would you associate Django framework with?", "correct_answer": "Python",
     "incorrect_answers": ["C#", "C++", "Java"]}
]
